### ISSUE TITLE
panic: interface is nil

### ISSUE THREAD

**Issue by stefa2k** [attestantio/vouch#10]
version `1.0.2`
```
vouch-a    | panic: interface conversion: interface {} is nil, not *v1.HeadEvent
vouch-a    |
vouch-a    | goroutine 180 [running]:
vouch-a    | github.com/attestantio/vouch/services/controller/standard.(*Service).HandleHeadEvent(0xc0001e0380, 0xc00115e100)
vouch-a    |    /app/services/controller/standard/events.go:27 +0x437
vouch-a    | github.com/attestantio/go-eth2-client/standardhttp/v1.(*Service).handleEvent(0xc00009e280, 0xc000698080, 0xc0004d0ab0)
vouch-a    |    /go/pkg/mod/github.com/attestantio/go-eth2-client@v0.6.15/standardhttp/v1/events.go:115 +0xe1
vouch-a    | github.com/attestantio/go-eth2-client/standardhttp/v1.(*Service).Events.func1.1(0xc000698080)
vouch-a    |    /go/pkg/mod/github.com/attestantio/go-eth2-client@v0.6.15/standardhttp/v1/events.go:53 +0x3d
vouch-a    | github.com/r3labs/sse/v2.(*Client).SubscribeWithContext.func1(0x0, 0x0)
vouch-a    |    /go/pkg/mod/github.com/r3labs/sse/v2@v2.3.0/client.go:89 +0x177
vouch-a    | gopkg.in/cenkalti/backoff%2ev1.RetryNotify(0xc0005b9ef8, 0x160ea20, 0xc000438120, 0x0, 0x5e418b, 0x1)
vouch-a    |    /go/pkg/mod/gopkg.in/cenkalti/backoff.v1@v1.1.0/retry.go:37 +0x9f
vouch-a    | github.com/r3labs/sse/v2.(*Client).SubscribeWithContext(0xc00014ca20, 0x1621da0, 0xc0003b8f80, 0x0, 0x0, 0xc000104f90, 0x0, 0x459246)
vouch-a    |    /go/pkg/mod/github.com/r3labs/sse/v2@v2.3.0/client.go:99 +0x11b
vouch-a    | github.com/r3labs/sse/v2.(*Client).SubscribeRawWithContext(...)
vouch-a    |    /go/pkg/mod/github.com/r3labs/sse/v2@v2.3.0/client.go:228
vouch-a    | github.com/attestantio/go-eth2-client/standardhttp/v1.(*Service).Events.func1(0xc00014ca20, 0x1621da0, 0xc0003b8f80, 0xc00009e280, 0xc0004d0ab0)
vouch-a    |    /go/pkg/mod/github.com/attestantio/go-eth2-client@v0.6.15/standardhttp/v1/events.go:52 +0x8f
vouch-a    | created by github.com/attestantio/go-eth2-client/standardhttp/v1.(*Service).Events
vouch-a    |    /go/pkg/mod/github.com/attestantio/go-eth2-client@v0.6.15/standardhttp/v1/events.go:51 +0x3a6
```

beacon-node-address: lighthouse 1.0.4

**Comment by stefa2k** [comment]
moving back to lighthouse `1.0.3` resolves the issue
