### ISSUE TITLE
Vouch crashes when only fee recipient is specified for each pubkey

### ISSUE THREAD

**Issue by zheli** [attestantio/vouch#112]
I tried to follow the README and configure different fee recipient for some pubkeys, but vouch always crashes. I am using the latest 1.6.3 version.

My execution layer configuration is something similar to this:
```
{
  "proposer_config": {
    "0xaaaa…aaaa": {
      "fee_recipient": "0x1111…1111"
      }
    },
    "0xbbbb…bbbb": {
      "fee_recipient": "0x2222…2222"
    }
  },
  "default_config": {
    "fee_recipient": "0x0123…cdef",
    "builder": {
      "enabled": true,
      "relays": [
        "https://relay1.example.com/",
        "https://relay2.example.com/"
      ]
    }
  }
}
```

And I would get runtime error like this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe21d39]

goroutine 49 [running]:
github.com/attestantio/vouch/services/blockrelay/standard.(*Service).submitValidatorRegistrationsForAccounts(0xc0004b4c80, {0x15a9c70, 0xc00078e080}, 0xc0006fc210)
	/app/services/blockrelay/standard/submitvalidatorregistrations.go:162 +0x879
github.com/attestantio/vouch/services/blockrelay/standard.(*Service).submitValidatorRegistrations(0xc0004b4c80, {0x15a9c70, 0xc00078e080}, {0x45d8e5, 0xc000a0cfd0})
	/app/services/blockrelay/standard/submitvalidatorregistrations.go:91 +0x19d
github.com/attestantio/vouch/services/blockrelay/standard.New.func1({0x15a9c70, 0xc00078e080})
	/app/services/blockrelay/standard/service.go:108 +0x34
created by github.com/attestantio/vouch/services/blockrelay/standard.New
	/app/services/blockrelay/standard/service.go:107 +0x7ef
```

But if I add a builder_config to each pubkey then it would work fine.
```
{
  "proposer_config": {
    "0xaaaa…aaaa": {
      "fee_recipient": "0x1111…1111",
      "builder": {
        "enabled": true,
        "relays": [
          "https://relay1.example.com/",
          "https://relay2.example.com/"
        ]
      }
    },
    "0xbbbb…bbbb": {
      "fee_recipient": "0x2222…2222",
      "builder": {
        "enabled": true,
        "relays": [
          "https://relay1.example.com/",
          "https://relay2.example.com/"
        ]
      }
    }
  },
  "default_config": {
    "fee_recipient": "0x0123…cdef",
    "builder": {
      "enabled": true,
      "relays": [
        "https://relay1.example.com/",
        "https://relay2.example.com/"
      ]
    }
  }
}
```

**Comment by mcdee** [comment]
This is addressed in #107 and will be available in the next release.
