### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [attestantio/vouch#90]
Vouch Version: `1.6.1`

Sometimes in logs I see:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd33d6d]

goroutine 143920 [running]:
github.com/attestantio/vouch/services/beaconblockproposer/standard.(*Service).proposeBlockWithAuction(0xc000167ef0, {0x15b80d0, 0xc00007ed40}, {0x8000000000000000, 0x318debf90e6, 0x1e52fa0}, 0xc000bc9000, {0x1e88860, 0x0, 0x0})
        /app/services/beaconblockproposer/standard/propose.go:291 +0x17ad
github.com/attestantio/vouch/services/beaconblockproposer/standard.(*Service).proposeBlock(0xc000167ef0, {0x15b80d0, 0xc00007ed40}, {0x64, 0x1f4, 0x1e52fa0}, 0x1, {0x1e88860, 0x0, 0x0})
        /app/services/beaconblockproposer/standard/propose.go:119 +0x95
github.com/attestantio/vouch/services/beaconblockproposer/standard.(*Service).Propose(0xc000167ef0, {0x15b80d0, 0xc00007ed40}, {0x11c1560, 0xc000bc9000})
        /app/services/beaconblockproposer/standard/propose.go:101 +0x77e
github.com/attestantio/vouch/services/scheduler/advanced.(*Service).ScheduleJob.func1()
        /app/services/scheduler/advanced/service.go:140 +0x364
created by github.com/attestantio/vouch/services/scheduler/advanced.(*Service).ScheduleJob
        /app/services/scheduler/advanced/service.go:104 +0x3d9
```
It started after I added `MeV`.
I have two instances of `vouch` connected to the three `dirks` with about 2000 keys.
Here example of `blockrelay` config:
```
{
  "default_config": {
    "builder": {
      "enabled": true,
      "relays": [
        "https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-goerli.flashbots.net/",
        "https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.max-profit.builder.goerli.blxrbdn.com/"
      ]
    },
    "fee_recipient": "0xccc...bbbb"
  },
  "proposer_config": {
    "0xffaa...bbbb": {
      "builder": {
        "enabled": true,
        "relays": [
          "https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-goerli.flashbots.net/",
          "https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.max-profit.builder.goerli.blxrbdn.com/"
        ]
      },
      "fee_recipient": "0xaaa...bbbb"
    },
    "0xffff...aaaa": {
      "builder": {
        "enabled": true,
        "relays": [
          "https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-goerli.flashbots.net/",
          "https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.max-profit.builder.goerli.blxrbdn.com/"
        ]
      },
      "fee_recipient": "0xaaa...bbbb"
    }
   }
 }
 ```
 In `proposer_config` I have rewrites for all 2000 keys.

**Comment by mcdee** [comment]
This issue has been fixed in 64cd0c01 and will be made available in Vouch 1.6.2, which is expected to be released in the next few days.

**Comment by SpontaneousOverthrow** [comment]
am I correct that this issue related to changing fee recipient address?

**Comment by mcdee** [comment]
Vouch 1.6.2 has been released.
